// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erppahfvabwigtjrcipm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVycHBhaGZ2YWJ3aWd0anJjaXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3ODEyMDgsImV4cCI6MjA2NTM1NzIwOH0.zDp_ACtI4gj0jbdbotQeOEQaWhoGwvZe4f-RHqx_4iI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);